### ISSUE TITLE
行 1503

### ISSUE THREAD

**Issue by pengcw** [hprose/hprose-aauto#2]
`attempt to`:perform arithmetic on
`kind`:variable(local)
`name`:'pos'
`type`:null
参数位置:0
数据类型:null
变量值:null

**Comment by andot** [comment]
1503 行是个括号，看不出哪儿有问题来啊

**Comment by pengcw** [comment]
感谢回复,不好意思，是1502行，我自己在前面加了个if(pos)

**Comment by andot** [comment]
什么情况下会出错，是什么引起的？仅凭现在提供的这些信息我没法确定该怎么改。你的这个错误我也没法复现。

**Comment by pengcw** [comment]
服务器新浪sae，框架是thinkphp3.2.3
我打印了参数 cookieList 的值: 
参数位置:1
数据类型:table
变量值: {
    [1] = PHPSESSID=ea1ff7774a721b472210f32a276eba76; path=/; HttpOnly
}
序列数组长度:   1
貌似是由于多了个 HttpOnly 不是键值对引起的pos为空
thinkphp 有个参数可以设置这个属性
'COOKIE_HTTPONLY'       =>  '',     // Cookie的httponly属性 3.2.2新增
服务端不是我的，不知道是不是设置了这个的原因
我目前在前面加了 if(pos) ，可以正常使用，不晓得有没副作用
希望能有帮助

**Comment by andot** [comment]
哦，原来如此，我明白了。加上 if (pos !== null) 应该可以
